easy_admin:
    site_name: 'Leboncoin admin'
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'username'}
                    - { property: 'email'}
                    - { property: 'enabled'}
                    - { property: 'acceptNewsletter'}
                    - { property: 'lastLogin' }
            form:
                fields:
                    - { property: 'username'}
                    - { property: 'email'}
                    - { property: 'enabled'}
                    - { property: 'acceptNewsletter'}
                    - { property: 'phone'}
                    - { property: 'lastLogin', format: 'd/m/Y'}
            search:
                fields: ['username', 'email']
        Announce:
            class: App\Entity\Ad
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'type'}
                    - { property: 'title'}
                    - { property: 'price'}
            form:
                fields:
                    - { property: 'type', type: 'choice', type_options: {required: true, choices: {'sell':'sell', 'buy':'buy'}}}
                    - { property: 'title'}
                    - { property: 'text'}
                    - { property: 'price'}
                    - { property: 'hidePhone'}
                    - { property: 'createdAt'}
                    - { property: 'user', type_options: {required: true} }
                    - { property: 'category', type_options: {required: true} }
                    - { property: 'city', type_options: {required: true} }
        City:
            class: App\Entity\City
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'name'}
                    - { property: 'zipcode'}
            form:
                fields:
                    - { property: 'name'}
                    - { property: 'zipcode'}
            search:
                fields: ['name', 'zipcode']
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'name'}
            form:
                fields:
                    - { property: 'name'}