fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address:        noreply@ioana.test
        sender_name:    Ioana Hazsda
    registration:
        form:
          type: AppBundle\Form\RegistrationType
